// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbpokljexxmwxuudhhmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNicG9rbGpleHhtd3h1dWRoaG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0OTg4NzEsImV4cCI6MjA3ODA3NDg3MX0.kBPefVYBPN-5I_o6sD17eGi1WVlo3l0t9jD0q7M980U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});